gpu: 'cuda:1'
lr: 2e-4
min_lr: 1e-7
weight_decay: 0.0
epochs: 5
warmup_epochs: 0.7
patience_epochs: 0.3
load_model: None
log_every_n_steps: 50

model: 
  name: 'SE3Transformer'
  num_layers: 3
  atom_feature_size: 28
  num_channels: 8
  num_degrees: 4
  edge_dim: 4
  div: 4
  pooling: 'avg'
  n_heads: 2
  cutoff: 5.0
  max_num_neighbors: 32

dataset:
  batch_size: 256
  num_workers: 8
  valid_size: 0.05
  ani1: True
  ani1x: True
  std: 0.2
  seed: 777